name: Volkszaehler Middleware
slug: volkszaehler
version: "1.1.0"
description: Volkszaehler Middleware as Home Assistant Add-on (uses core-mariadb)
arch:
  - amd64
  - aarch64
startup: services
boot: auto

ports:
  80/tcp: 8080

ports_description:
  80/tcp: "Volkszaehler Weboberfl√§che (HTTP)"

ingress: true
panel_icon: mdi:flash
panel_title: Volkszaehler
init: false

options:
  db_host: core-mariadb
  db_port: 3306
  db_user: vz
  db_password: demo
  db_name: volkszaehler
  db_admin_user: vz_admin
  db_admin_password: admin_demo

schema:
  db_host: str
  db_port: int
  db_user: str
  db_password: password
  db_name: str
  db_admin_user: str
  db_admin_password: password

map:
  - share:rw
