name: Volkszaehler Middleware
slug: volkszaehler
version: "1.0.12"
description: Volkszaehler Middleware as Home Assistant Add-on (uses core-mariadb)
arch:
  - amd64
  - aarch64
startup: services
boot: auto
ports:
  80/tcp: 8080
ports_description:
  80/tcp: "Volkszaehler Weboberfl√§che (HTTP)"
  
ingress: true
panel_icon: mdi:flash
panel_title: Volkszaehler
init: false

options: {}
schema: {}

map:
  - share:rw
