name: Volkszaehler Middleware
slug: volkszaehler
version: "1.0.8"
description: Volkszaehler Middleware as Home Assistant Add-on (uses core-mariadb)
arch:
  - amd64
  - aarch64
startup: services
boot: auto
ports:
  8080/tcp: 8080
ingress: true
ingress_port: 80
panel_icon: mdi:flash
panel_title: Volkszaehler
init: false

options: {}
schema: {}

map:
  - share:rw
